### ISSUE TITLE
how about an online version?

### ISSUE THREAD

**Issue by erichexter** [Haacked/SeeGit#74]
Have you thought about a version of SeeGit that could show the commit history and branching of a github repo?  That would be pretty cool.

**Comment by Haacked** [comment]
Hmm, that would be cool. The site would have to clone the repository so it could end up taking a lot of disk space if a lot of folks use it. Also, the point of SeeGit is to be interactive. As you make commits, it shows the changes in real time. That'd be harder with a web version.

So I still like the idea, but not something I plan to do anytime soon.
