### ISSUE TITLE
Add the username who made the commit

### ISSUE THREAD

**Issue by jasekiw** [Haacked/SeeGit#85]
For each commit listed please add the ability to view the author of that commit. I think it would make it much better to read

**Comment by Haacked** [comment]
:+1: Want to submit a PR? :smile:

**Comment by ben-m-lucas** [comment]
This was implemented with PR #86

**Comment by Haacked** [comment]
For future reference, if a commit fixes an existing issue, you can put `Fixes #86` in the body of the commit message and when it gets merged to `master`, GitHub will automatically close the issue.
